{%- extends 'template_html.tpl' -%}

{% block header %}

<link rel="shortcut icon" href="images/icons/loiseau.jpg">
<link rel="stylesheet" href="css/custom.css">

<html lang="en-us">
  <head>
    <meta charset="UTF-8">
    <!-- Change name of the website here -->
    <title>Romain Loiseau</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  
{{ super() }}

{% endblock header%}

{% block body %}

<!-- Change colors here -->
<div style="--color_left:#80cc28;--color_right:#00aec7">

<!-- Change menu here -->
<ul id="menu-deroulant">
    <li><a href="index.html">Home</a></li>
    <li><a href="">Projects</a>
    <ul>
        <li><a href="https://romainloiseau.github.io/deep-linear-shapes/">Deep Linear Shapes</a></li>
    </ul>
    </li>
    <li style="float:right"><a href="">Up</a></li>
</ul>

{{ super() }}

<footer class="site-footer">
  <!-- Change footer here -->
	<span class="site-footer-owner"><a href="index.html">Romain Loiseau - IMAGINE/ENPC & Lastig/IGN</a> is maintained by <a href="index.html">Romain Loiseau</a>.</span>
  <span class="site-footer-credits">This page was generated by a template written by <a href="index.html">Romain Loiseau</a>.</span>

</footer>
</section>

</div>  
{% endblock body %}
